# Generated by Django 2.0.7 on 2018-11-28 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Category'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Organizer'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
