# Generated by Django 2.0.7 on 2018-11-29 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20181128_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
